### ISSUE TITLE
License file?

### ISSUE THREAD

**Issue by obscurerichard** [finitud/vagrant-common-lisp#6]
Would you consider adding a license file to this project?

For maximum compatibility with other Vagrant projects, I'd suggest the MIT license, such as expressed here:

https://github.com/intel352/vagrant-shell-scripts/blob/master/LICENSE.md

(replace the copyright statement with your copyright, of course)

**Comment by finitud** [comment]
Many thanks for the suggestion, I have added the relevant file and comment on the readme file.

**Comment by obscurerichard** [comment]
Thanks!
